jobs = [
        {"company":"Google","title":"Software Engineer","location":"Bangalore","salary":"₹18-25 LPA","experience":"Fresher","type":"Full Time","skills":["Java","SQL","Spring Boot"]},
        {"company":"Microsoft","title":"Data Analyst","location":"Hyderabad","salary":"₹10-15 LPA","experience":"0-2 Years","type":"Full Time","skills":["Power BI","Excel","SQL"]},
        {"company":"Amazon","title":"Cloud Engineer","location":"Hyderabad","salary":"₹15-22 LPA","experience":"1 Year","type":"Full Time","skills":["AWS","Docker","Linux"]},
        {"company":"Infosys","title":"Python Developer","location":"Pune","salary":"₹8-12 LPA","experience":"Fresher","type":"Full Time","skills":["Python","Flask","MySQL"]},
        {"company":"TCS","title":"Java Developer","location":"Chennai","salary":"₹7-10 LPA","experience":"Fresher","type":"Full Time","skills":["Java","Spring","MySQL"]},
        {"company":"Accenture","title":"Frontend Developer","location":"Hyderabad","salary":"₹8-11 LPA","experience":"0-2 Years","type":"Full Time","skills":["HTML","CSS","JavaScript"]},
        {"company":"IBM","title":"AI Engineer","location":"Bangalore","salary":"₹14-20 LPA","experience":"1 Year","type":"Full Time","skills":["Python","TensorFlow","ML"]},
        {"company":"Oracle","title":"Database Developer","location":"Hyderabad","salary":"₹9-14 LPA","experience":"1 Year","type":"Full Time","skills":["Oracle","SQL","PL/SQL"]},
        {"company":"Wipro","title":"React Developer","location":"Pune","salary":"₹8-12 LPA","experience":"Fresher","type":"Full Time","skills":["React","JavaScript","Bootstrap"]},
        {"company":"Capgemini","title":"Full Stack Developer","location":"Hyderabad","salary":"₹10-14 LPA","experience":"1 Year","type":"Full Time","skills":["Python","React","MySQL"]},
        {"company":"Tech Mahindra","title":"SQL Developer","location":"Noida","salary":"₹7-10 LPA","experience":"Fresher","type":"Full Time","skills":["SQL","MySQL","Oracle"]},
        {"company":"Cognizant","title":"Power BI Developer","location":"Chennai","salary":"₹8-12 LPA","experience":"1 Year","type":"Full Time","skills":["Power BI","DAX","SQL"]},
        {"company":"HCL","title":"Network Engineer","location":"Noida","salary":"₹7-11 LPA","experience":"Fresher","type":"Full Time","skills":["CCNA","Networking","Linux"]},
        {"company":"Deloitte","title":"Cyber Security Analyst","location":"Hyderabad","salary":"₹11-16 LPA","experience":"1 Year","type":"Full Time","skills":["Security","Python","Linux"]},
        {"company":"EY","title":"Business Analyst","location":"Bangalore","salary":"₹10-15 LPA","experience":"0-2 Years","type":"Full Time","skills":["Excel","Power BI","SQL"]},
        {"company":"Zoho","title":"Backend Developer","location":"Chennai","salary":"₹9-13 LPA","experience":"Fresher","type":"Full Time","skills":["Python","Django","API"]},
        {"company":"Adobe","title":"UI/UX Designer","location":"Bangalore","salary":"₹10-16 LPA","experience":"1 Year","type":"Full Time","skills":["Figma","Adobe XD","Photoshop"]},
        {"company":"SAP","title":"Data Engineer","location":"Hyderabad","salary":"₹13-17 LPA","experience":"2 Years","type":"Full Time","skills":["Python","SQL","ETL"]},
        {"company":"Paytm","title":"Android Developer","location":"Noida","salary":"₹10-14 LPA","experience":"Fresher","type":"Full Time","skills":["Java","Kotlin","Android"]},
        {"company":"PhonePe","title":"Flutter Developer","location":"Bangalore","salary":"₹11-15 LPA","experience":"1 Year","type":"Full Time","skills":["Flutter","Dart","Firebase"]},
        {"company":"Flipkart","title":"DevOps Engineer","location":"Bangalore","salary":"₹14-18 LPA","experience":"2 Years","type":"Full Time","skills":["Docker","Kubernetes","AWS"]},
        {"company":"Cisco","title":"QA Engineer","location":"Hyderabad","salary":"₹9-13 LPA","experience":"Fresher","type":"Full Time","skills":["Testing","Selenium","Java"]},
        {"company":"HSBC","title":"Automation Tester","location":"Pune","salary":"₹10-14 LPA","experience":"1 Year","type":"Full Time","skills":["Selenium","Java","TestNG"]},
        {"company":"Intel","title":"Embedded Engineer","location":"Bangalore","salary":"₹12-18 LPA","experience":"1 Year","type":"Full Time","skills":["C","C++","Linux"]},
        {"company":"NVIDIA","title":"GPU Software Engineer","location":"Pune","salary":"₹18-24 LPA","experience":"2 Years","type":"Full Time","skills":["C++","CUDA","Python"]},
        {"company":"Qualcomm","title":"Firmware Engineer","location":"Hyderabad","salary":"₹15-20 LPA","experience":"2 Years","type":"Full Time","skills":["Embedded C","Linux","RTOS"]},
        {"company":"Samsung","title":"Software Developer","location":"Noida","salary":"₹12-18 LPA","experience":"Fresher","type":"Full Time","skills":["Java","Spring","SQL"]},
        {"company":"LTIMindtree","title":"Angular Developer","location":"Mumbai","salary":"₹9-13 LPA","experience":"1 Year","type":"Full Time","skills":["Angular","TypeScript","HTML"]},
        {"company":"Hexaware","title":"Machine Learning Engineer","location":"Chennai","salary":"₹12-17 LPA","experience":"1 Year","type":"Full Time","skills":["Python","Scikit-learn","Pandas"]},
        {"company":"Persistent","title":"Data Scientist","location":"Hyderabad","salary":"₹14-20 LPA","experience":"2 Years","type":"Full Time","skills":["Python","ML","Power BI"]}
    ]